# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExcelMergeUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(12, 12, 68, 24))
        self.label_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(82, 65, 81, 24))
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.fileTypeComboBox = QtWidgets.QComboBox(self.frame)
        self.fileTypeComboBox.setGeometry(QtCore.QRect(170, 65, 171, 28))
        self.fileTypeComboBox.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.fileTypeComboBox.setObjectName("fileTypeComboBox")
        self.fileTypeComboBox.addItem("")
        self.fileTypeComboBox.addItem("")
        self.fileTypeComboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(82, 100, 81, 24))
        self.label_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.skipRowEdit = QtWidgets.QLineEdit(self.frame)
        self.skipRowEdit.setGeometry(QtCore.QRect(170, 100, 171, 27))
        self.skipRowEdit.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.skipRowEdit.setObjectName("skipRowEdit")
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 4)
        self.inputFolderButton = QtWidgets.QPushButton(self.centralwidget)
        self.inputFolderButton.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.inputFolderButton.setObjectName("inputFolderButton")
        self.gridLayout.addWidget(self.inputFolderButton, 0, 3, 1, 1)
        self.outputFileEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.outputFileEdit.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.outputFileEdit.setObjectName("outputFileEdit")
        self.gridLayout.addWidget(self.outputFileEdit, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.inputFolderEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.inputFolderEdit.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.inputFolderEdit.setObjectName("inputFolderEdit")
        self.gridLayout.addWidget(self.inputFolderEdit, 0, 2, 1, 1)
        self.outputFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.outputFileButton.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.outputFileButton.setObjectName("outputFileButton")
        self.gridLayout.addWidget(self.outputFileButton, 1, 3, 1, 1)
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 5, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ExcelMerge"))
        self.label_3.setText(_translate("MainWindow", "Options"))
        self.label_4.setText(_translate("MainWindow", "File Type"))
        self.fileTypeComboBox.setItemText(0, _translate("MainWindow", "xls"))
        self.fileTypeComboBox.setItemText(1, _translate("MainWindow", "xlsx"))
        self.fileTypeComboBox.setItemText(2, _translate("MainWindow", "xls & xlsx"))
        self.label_5.setText(_translate("MainWindow", "Skip Row"))
        self.inputFolderButton.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Input Folder"))
        self.label_2.setText(_translate("MainWindow", "Output File"))
        self.outputFileButton.setText(_translate("MainWindow", "..."))
        self.runButton.setText(_translate("MainWindow", "Run"))

